### ISSUE TITLE
Data for training MineCLIP

### ISSUE THREAD

**Issue by yifan123** [MineDojo/MineCLIP#1]
Hi,
Thanks for these amazing results and for releasing the code!
Do you plan to also release the 640K video-language pairs for training MineCLIP you mention in the paper ?

**Comment by yunfanjiang** [comment]
Hey, please follow the [instruction](http://docs.minedojo.org/sections/getting_started/data.html#youtube-database) to download the YouTube data. Let me know if you have further questions. Thanks!

**Comment by yifan123** [comment]
MINEDOJO: knowledge base: 730K+(~300K hours)
MINECLIP: 640k video-language pairs, 640K*16s=2.8K hours.
I know how to download the YouTube data (300K hours), but I can't find the filterd 640K data used to train MineCLIP. Where can I download it?
Thanks~

**Comment by wangguanzhi** [comment]
Hi @yifan123! Thanks for your interest. Here is how we extracted 640K pairs. Feel free to use other heuristics to extract training pairs from 730K+ videos.

1. Collect a list of keywords corresponding to the supported entities, blocks, and items in Minecraft;
2. Perform string matching over our YouTube video transcripts to obtain 640K text segments;
3. For each matched transcript segment, randomly grow it to 16 ∼ 77 tokens (limited by CLIP’s context length);
4. Randomly sample a timestamp within the start and end time of the matched transcript as the center for the video clip;
5. Randomly grow the video clip from the center timestamp to 8 ∼ 16 seconds.

**Comment by yifan123** [comment]
Thanks for your reply. I have a few more questions.
1. Compared with the 400M data used by CLIP, MineCLIP uses a little less data of 640K to finetune, does it seriously limit the performance?
2. In comparative learning, the larger the batch, the better. What is the reason for mineCLIP to choose small batch(64*8)?
3. What is the reason for finetuning only two epochs?

Thanks~

**Comment by wangguanzhi** [comment]
1.  We initialized MineCLIP weights from OpenAI CLIP’s [public checkpoint](https://github.com/openai/CLIP) and only finetuned the last two layers during training. Therefore, MineCLIP was not trained from scratch and we found that 640K video-text pairs already gave a satisfactory performance.
2. We followed [VideoCLIP](https://arxiv.org/abs/2109.14084) which also uses 512 batch size. Note that our visual inputs are videos instead of images. We sampled 16 RGB frames from each video uniformly.
3. We did not do too much hyperparameter tuning. So it's possible that finetuning for more epochs would give better performance.

**Comment by yunfanjiang** [comment]
Thanks @wangguanzhi for the detailed explanation. I'm closing this issue now. Feel free to reopen with new questions. Thanks @yifan123 again for your interest.

**Comment by yifan123** [comment]
Thanks for your replay!

Could you share your script of cleaning data?

> Hi @yifan123! Thanks for your interest. Here is how we extracted 640K pairs. Feel free to use other heuristics to extract training pairs from 730K+ videos.
> 
> 1. Collect a list of keywords corresponding to the supported entities, blocks, and items in Minecraft;
> 2. Perform string matching over our YouTube video transcripts to obtain 640K text segments;
> 3. For each matched transcript segment, randomly grow it to 16 ∼ 77 tokens (limited by CLIP’s context length);
> 4. Randomly sample a timestamp within the start and end time of the matched transcript as the center for the video clip;
> 5. Randomly grow the video clip from the center timestamp to 8 ∼ 16 seconds.

**Comment by wangguanzhi** [comment]
DM you!

**Comment by LightHouse2000** [comment]
> DM you!

hey! Thanks for your amazing work!

would you mind sharing your scripts for cleanning data once more?

**Comment by wangguanzhi** [comment]
> 

Can you give me your email?

**Comment by wangguanzhi** [comment]
> > DM you!
> 
> hey! Thanks for your amazing work!
> 
> would you mind sharing your scripts for cleanning data once more?

Can you give me your email?

**Comment by yifan123** [comment]
> Hi @yifan123! Thanks for your interest. Here is how we extracted 640K pairs. Feel free to use other heuristics to extract training pairs from 730K+ videos.
> 
> 1. Collect a list of keywords corresponding to the supported entities, blocks, and items in Minecraft;
> 2. Perform string matching over our YouTube video transcripts to obtain 640K text segments;
> 3. For each matched transcript segment, randomly grow it to 16 ∼ 77 tokens (limited by CLIP’s context length);
> 4. Randomly sample a timestamp within the start and end time of the matched transcript as the center for the video clip;
> 5. Randomly grow the video clip from the center timestamp to 8 ∼ 16 seconds.

Hey,
 
Depending on the keyword you provide, each video can matches about 30 keywords. Therefore, we can extract about 700k*30=20M pairs from 730K+ videos following the above filtering process. Intuitively, these pairs have low quality. For example, the voice often talks about something in the future, which does not match the current video, such as diamond. As mentioned in the paper, only 640K pair was extracted at last. Is there any other post-processing?

**Comment by LightHouse2000** [comment]
> 
Thanks a lot！
pkulighthouse@163.com

**Comment by wangguanzhi** [comment]
> > Hi @yifan123! Thanks for your interest. Here is how we extracted 640K pairs. Feel free to use other heuristics to extract training pairs from 730K+ videos.
> > 
> > 1. Collect a list of keywords corresponding to the supported entities, blocks, and items in Minecraft;
> > 2. Perform string matching over our YouTube video transcripts to obtain 640K text segments;
> > 3. For each matched transcript segment, randomly grow it to 16 ∼ 77 tokens (limited by CLIP’s context length);
> > 4. Randomly sample a timestamp within the start and end time of the matched transcript as the center for the video clip;
> > 5. Randomly grow the video clip from the center timestamp to 8 ∼ 16 seconds.
> 
> Hey,
> 
> Depending on the keyword you provide, each video can matches about 30 keywords. Therefore, we can extract about 700k*30=20M pairs from 730K+ videos following the above filtering process. Intuitively, these pairs have low quality. For example, the voice often talks about something in the future, which does not match the current video, such as diamond. As mentioned in the paper, only 640K pair was extracted at last. Is there any other post-processing?

Just replied to your email!

**Comment by ZhiyuuanS** [comment]
Hi, can you share the script with me as well?
zhiyuan.sun@umontreal.ca. 

Thanks in advance

**Comment by phython96** [comment]
Hi, could you please share the script with me?
caishaofei@stu.pku.edu.cn

Thanks a lot!

**Comment by salamentic** [comment]
Hey! Sorry for bumping this old thread, but I was hoping to get the script for cleaning the data as well. Thanks!

anrao@umich.edu

**Comment by wangguanzhi** [comment]
We just released the transcript annotations. See https://github.com/MineDojo/MineCLIP#training-data
